dist: focal
language: python
python:
  # - "3.6"
  # - "3.7"
  - "3.8"
# services:
#   - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
env:
  global:
  - PGPORT=5433
  - PGUSER=travis
  # - NACCBIS_DB_URL=postgresql://$PGUSER@:$PGPORT/naccbisdb
  - SQLALCHEMY_WARN_20=1 # see https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#deprecation-20-mode
install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt
before_script:
  - psql -c "create database naccbisdb;"
  - psql naccbisdb -c "select version()"
script:
  # lint
  - bash scripts/lint.sh
  # test
  - echo $PGPORT
  - echo $PGUSER
  - pytest -vs --cov --cov-report term
after_success: codecov --required
