language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - touch conf.py
  - pip install pipenv
  - pipenv install --dev
script:
  - pytest -m "not integration" --cov --cov-report term
  - flake8 naccbis --statistics
  - mypy naccbis/
after_success: codecov --required
