dist: focal
language: python
python:
  # - "3.6"
  # - "3.7"
  - "3.8"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres travis_ci_test -c "select version()"
install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt
script:
  # lint
  - bash scripts/lint.sh
  # test
  - pytest -m "not integration" --cov --cov-report term
after_success: codecov --required
