dist: focal
language: python
python:
  # - "3.6"
  # - "3.7"
  - "3.8"
# services:
#   - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
env:
  global:
  - PGPORT=5433
  - PGUSER=travis
install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt
before_script:
  - psql -c "create database naccbisdb;"
  - psql naccbisdb -c "select version()"
script:
  # lint
  - bash scripts/lint.sh
  # test
  - pytest --cov --cov-report term
after_success: codecov --required
