language: python
python:
  # - "3.6"
  # - "3.7"
  - "3.8"
install:
  - touch conf.py
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt
script:
  # lint
  - bash scripts/lint.sh
  # test
  - pytest -m "not integration" --cov --cov-report term
after_success: codecov --required
