language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements-dev.txt
  - touch conf.py
  - pip install -e .
script:
  - pytest -m "not integration" --cov-report term
  - flake8 naccbis --statistics --ignore=E501 # temporarily ignore line length
after_success: codecov
