language: python
matrix:
  include:
    - name: "Unit Tests"
      python: "3.6"
install:
  - pip install -r requirements-dev.txt
  - touch conf.py
  - pip install -e .
script: pytest -m "not integration"
