language: python
python:
  # - "3.6"
  - "3.7"
  # - "3.8"
install:
  - touch conf.py
  - pip install pipenv
  - pipenv install --dev
script:
  # lint
  - mypy naccbis/
  - flake8 naccbis tests --statistics
  - black naccbis tests --check || true # don't fail the build for now
  # test
  - pytest -m "not integration" --cov --cov-report term
after_success: codecov --required
