language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements-dev.txt
  - touch conf.py
  - pip install -e .
script: pytest -m "not integration" --cov-report term
after_success: codecov
