dist: focal
language: python
python:
  # - "3.6"
  # - "3.7"
  - "3.8"
services:
  - postgresql
install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt
before_script:
  - psql -U travis -p 5433 -c "create database travis_ci_test;"
  - psql -U travis travis_ci_test -c "select version()"
script:
  # lint
  - bash scripts/lint.sh
  # test
  - pytest -m "not integration" --cov --cov-report term
after_success: codecov --required
