version: '3'

volumes:
  pgdata:

services:
  web:
    build: .
    command: gunicorn --bind 127.0.0.1:8001 --access-logfile - webapp.wsgi
    container_name: naccbis_web
    # ports:
    #   - 8001:8001
    network_mode: host
    environment:
      - "DEBUG=1"
  api:
    build: .
    command: /start_api.sh
    container_name: naccbis_api
    # ports:
    #   - 8000:8000
    network_mode: host
  db:
    image: postgres:12
    container_name: naccbisdb
    restart: always
    environment:
      - "POSTGRES_PASSWORD=mypassword"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    ports:
      - 5431:5432
