target-version = "py39"
line-length = 88

select = [
    "E",   # pycodestyle
    "F",   # Pyflakes
    "W",   # pycodestyle
    "C90", # McCabe
    "B",   # flake8-bugbear
    "I",   # isort
    "N",   # pep8-naming
    "UP",  # pyupgrade
    "ERA", # flake8-eradicate
]

ignore = [
    "E501",   # line length (handled mostly by Black)
    # "E203", # whitespace before ':'
    "B008",   # do not perform function calls in argument defaults (for FastAPI)
]
