create table raw_pitchers_conference (
  No integer,
  Name varchar(35),
  Team varchar(5),
  Season integer,
  Yr varchar(2),
  Pos varchar(15),
  G integer,
  GS integer,
  W integer,
  L integer,
  SV integer,
  CG integer,
  IP varchar(20),
  H integer,
  R integer,
  ER integer,
  BB integer,
  SO integer,
  SO_9 numeric,
  HR integer,
  ERA numeric,
  primary key (Name, Team, Season)
)
