create table raw_game_log_hitting (
  Date varchar(10),
  Season integer,
  Name varchar(30),
  Opponent text,
  Score varchar(10),
  AB integer,
  R integer,
  H integer,
  x2B integer,
  x3B integer,
  HR integer,
  RBI integer,
  BB integer,
  SO integer,
  SB integer,
  CS integer,
  HBP integer,
  SF integer,
  SH integer,
  TB integer,
  XBH integer,
  GDP integer,
  GO integer,
  FO integer,
  GO_FO numeric,
  PA integer
)
