create table raw_team_pitching_overall (
  Name varchar(30),
  Season integer,
  G integer,
  W integer,
  L integer,
  SV integer,
  CG integer,
  SHO integer,
  IP varchar(20),
  H integer,
  R integer,
  ER integer,
  BB integer,
  SO integer,
  ERA numeric,
  x2B integer,
  x3B integer,
  HR integer,
  AB integer,
  AVG numeric,
  WP integer,
  HBP integer,
  BK integer,
  SF integer,
  SH integer,
  SO_9 numeric,
  primary key (Name, Season)
)
