create table raw_batters_conference (
  No integer,
  Name varchar(35),
  Team varchar(5),
  Season integer,
  Yr char(2),
  Pos varchar(15),
  G integer,
  PA integer,
  AB integer,
  R integer,
  H integer,
  x2B integer,
  x3B integer,
  HR integer,
  RBI integer,
  BB integer,
  SO integer,
  SB integer,
  CS integer,
  AVG numeric,
  OBP numeric,
  SLG numeric,
  HBP integer,
  SF integer,
  SH integer,
  TB integer,
  XBH integer,
  GDP integer,
  GO integer,
  FO integer,
  GO_FO numeric,
  primary key (Name, Team, Season)
);

create table raw_batters_conference_inseason (
  No integer,
  Name varchar(35),
  Team varchar(5),
  Season integer,
  Date date,
  Yr char(2),
  Pos varchar(15),
  G integer,
  PA integer,
  AB integer,
  R integer,
  H integer,
  x2B integer,
  x3B integer,
  HR integer,
  RBI integer,
  BB integer,
  SO integer,
  SB integer,
  CS integer,
  AVG numeric,
  OBP numeric,
  SLG numeric,
  HBP integer,
  SF integer,
  SH integer,
  TB integer,
  XBH integer,
  GDP integer,
  GO integer,
  FO integer,
  GO_FO numeric,
  primary key (Name, Team, Date)
);

create table raw_batters_overall (
  No integer,
  Name varchar(35),
  Team varchar(5),
  Season integer,
  Yr char(2),
  Pos varchar(15),
  G integer,
  PA integer,
  AB integer,
  R integer,
  H integer,
  x2B integer,
  x3B integer,
  HR integer,
  RBI integer,
  BB integer,
  SO integer,
  SB integer,
  CS integer,
  AVG numeric,
  OBP numeric,
  SLG numeric,
  HBP integer,
  SF integer,
  SH integer,
  TB integer,
  XBH integer,
  GDP integer,
  GO integer,
  FO integer,
  GO_FO numeric,
  primary key (Name, Team, Season)
);

create table raw_batters_overall_inseason (
  No integer,
  Name varchar(35),
  Team varchar(5),
  Season integer,
  Date date,
  Yr char(2),
  Pos varchar(15),
  G integer,
  PA integer,
  AB integer,
  R integer,
  H integer,
  x2B integer,
  x3B integer,
  HR integer,
  RBI integer,
  BB integer,
  SO integer,
  SB integer,
  CS integer,
  AVG numeric,
  OBP numeric,
  SLG numeric,
  HBP integer,
  SF integer,
  SH integer,
  TB integer,
  XBH integer,
  GDP integer,
  GO integer,
  FO integer,
  GO_FO numeric,
  primary key (Name, Team, Date)
);

create table raw_game_log_fielding (
  Game_num integer,
  Date varchar(10),
  Season integer,
  Name varchar(30),
  Opponent text,
  Score varchar(10),
  TC integer,
  PO integer,
  A integer,
  E integer,
  FPCT numeric,
  DP integer,
  SBA integer,
  CS integer,
  CSPCT numeric,
  PB integer,
  CI integer,
  primary key (Game_num, Date, Season, Name)
);

create table raw_game_log_fielding_inseason (
  Game_num integer,
  Scrape_date date,
  Date varchar(10),
  Season integer,
  Name varchar(30),
  Opponent text,
  Score varchar(10),
  TC integer,
  PO integer,
  A integer,
  E integer,
  FPCT numeric,
  DP integer,
  SBA integer,
  CS integer,
  CSPCT numeric,
  PB integer,
  CI integer,
  primary key (Game_num, Scrape_date, Name)
);

create table raw_game_log_hitting (
  Game_num integer,
  Date varchar(10),
  Season integer,
  Name varchar(30),
  Opponent text,
  Score varchar(10),
  AB integer,
  R integer,
  H integer,
  x2B integer,
  x3B integer,
  HR integer,
  RBI integer,
  BB integer,
  SO integer,
  SB integer,
  CS integer,
  HBP integer,
  SF integer,
  SH integer,
  TB integer,
  XBH integer,
  GDP integer,
  GO integer,
  FO integer,
  GO_FO numeric,
  PA integer,
  primary key (Game_num, Date, Season, Name)

);

create table raw_game_log_hitting_inseason (
  Game_num integer,
  Scrape_date date,
  Date varchar(10),
  Season integer,
  Name varchar(30),
  Opponent text,
  Score varchar(10),
  AB integer,
  R integer,
  H integer,
  x2B integer,
  x3B integer,
  HR integer,
  RBI integer,
  BB integer,
  SO integer,
  SB integer,
  CS integer,
  HBP integer,
  SF integer,
  SH integer,
  TB integer,
  XBH integer,
  GDP integer,
  GO integer,
  FO integer,
  GO_FO numeric,
  PA integer,
  primary key (Game_num, Scrape_date, Name)

);

create table raw_game_log_pitching (
  Game_num integer,
  Date varchar(10),
  Season integer,
  Name varchar(30),
  Opponent text,
  Score varchar(10),
  W integer,
  L integer,
  SV integer,
  IP varchar(20),
  H integer,
  R integer,
  ER integer,
  ERA numeric,
  BB integer,
  SO integer,
  HR integer,
  primary key (Game_num, Date, Season, Name)
);

create table raw_game_log_pitching_inseason (
  Game_num integer,
  Scrape_date date,
  Date varchar(10),
  Season integer,
  Name varchar(30),
  Opponent text,
  Score varchar(10),
  W integer,
  L integer,
  SV integer,
  IP varchar(20),
  H integer,
  R integer,
  ER integer,
  ERA numeric,
  BB integer,
  SO integer,
  HR integer,
  primary key (Game_num, Scrape_date, Name)

);

create table raw_pitchers_conference (
  No integer,
  Name varchar(35),
  Team varchar(5),
  Season integer,
  Yr varchar(2),
  Pos varchar(15),
  G integer,
  GS integer,
  W integer,
  L integer,
  SV integer,
  CG integer,
  IP varchar(20),
  H integer,
  R integer,
  ER integer,
  BB integer,
  SO integer,
  SO_9 numeric,
  HR integer,
  ERA numeric,
  primary key (Name, Team, Season)
);

create table raw_pitchers_conference_inseason (
  No integer,
  Name varchar(35),
  Team varchar(5),
  Season integer,
  Date date,
  Yr varchar(2),
  Pos varchar(15),
  G integer,
  GS integer,
  W integer,
  L integer,
  SV integer,
  CG integer,
  IP varchar(20),
  H integer,
  R integer,
  ER integer,
  BB integer,
  SO integer,
  SO_9 numeric,
  HR integer,
  ERA numeric,
  primary key (Name, Team, Date)
);

create table raw_pitchers_overall (
  No integer,
  Name varchar(35),
  Team varchar(5),
  Season integer,
  Yr char(2),
  Pos varchar(15),
  G integer,
  GS integer,
  W integer,
  L integer,
  SV integer,
  CG integer,
  SHO integer,
  IP varchar(20),
  H integer,
  R integer,
  ER integer,
  BB integer,
  SO integer,
  ERA numeric,
  x2B integer,
  x3B integer,
  HR integer,
  AB integer,
  AVG numeric,
  WP integer,
  HBP integer,
  BK integer,
  SF integer,
  SH integer,
  SO_9 numeric,
  primary key (Name, Team, Season)
);

create table raw_pitchers_overall_inseason (
  No integer,
  Name varchar(35),
  Team varchar(5),
  Season integer,
  Date date,
  Yr char(2),
  Pos varchar(15),
  G integer,
  GS integer,
  W integer,
  L integer,
  SV integer,
  CG integer,
  SHO integer,
  IP varchar(20),
  H integer,
  R integer,
  ER integer,
  BB integer,
  SO integer,
  ERA numeric,
  x2B integer,
  x3B integer,
  HR integer,
  AB integer,
  AVG numeric,
  WP integer,
  HBP integer,
  BK integer,
  SF integer,
  SH integer,
  SO_9 numeric,
  primary key (Name, Team, Date)
);

create table raw_team_fielding_conference (
  Name varchar(30),
  Season integer,
  G integer,
  TC integer,
  PO integer,
  A integer,
  E integer,
  FPCT numeric,
  DP integer,
  SBA integer,
  CS integer,
  CSPCT numeric,
  PB integer,
  CI integer,
  primary key (Name, Season)
);

create table raw_team_fielding_conference_inseason (
  Name varchar(30),
  Season integer,
  Date date,
  G integer,
  TC integer,
  PO integer,
  A integer,
  E integer,
  FPCT numeric,
  DP integer,
  SBA integer,
  CS integer,
  CSPCT numeric,
  PB integer,
  CI integer,
  primary key (Name, Date)
);

create table raw_team_fielding_overall (
  Name varchar(30),
  Season integer,
  G integer,
  TC integer,
  PO integer,
  A integer,
  E integer,
  FPCT numeric,
  DP integer,
  SBA integer,
  CS integer,
  CSPCT numeric,
  PB integer,
  CI integer,
  primary key (Name, Season)
);

create table raw_team_fielding_overall_inseason (
  Name varchar(30),
  Season integer,
  Date date,
  G integer,
  TC integer,
  PO integer,
  A integer,
  E integer,
  FPCT numeric,
  DP integer,
  SBA integer,
  CS integer,
  CSPCT numeric,
  PB integer,
  CI integer,
  primary key (Name, Date)
);

create table raw_team_offense_conference (
  Name varchar(30),
  Season integer,
  G integer,
  PA integer,
  AB integer,
  R integer,
  H integer,
  x2B integer,
  x3B integer,
  HR integer,
  RBI integer,
  BB integer,
  SO integer,
  SB integer,
  CS integer,
  AVG numeric,
  OBP numeric,
  SLG numeric,
  HBP integer,
  SF integer,
  SH integer,
  TB integer,
  XBH integer,
  GDP integer,
  GO integer,
  FO integer,
  GO_FO numeric,
  primary key (Name, Season)
);

create table raw_team_offense_conference_inseason (
  Name varchar(30),
  Season integer,
  Date date,
  G integer,
  PA integer,
  AB integer,
  R integer,
  H integer,
  x2B integer,
  x3B integer,
  HR integer,
  RBI integer,
  BB integer,
  SO integer,
  SB integer,
  CS integer,
  AVG numeric,
  OBP numeric,
  SLG numeric,
  HBP integer,
  SF integer,
  SH integer,
  TB integer,
  XBH integer,
  GDP integer,
  GO integer,
  FO integer,
  GO_FO numeric,
  primary key (Name, Season, Date)
);

create table raw_team_offense_overall (
  Name varchar(30),
  Season integer,
  G integer,
  PA integer,
  AB integer,
  R integer,
  H integer,
  x2B integer,
  x3B integer,
  HR integer,
  RBI integer,
  BB integer,
  SO integer,
  SB integer,
  CS integer,
  AVG numeric,
  OBP numeric,
  SLG numeric,
  HBP integer,
  SF integer,
  SH integer,
  TB integer,
  XBH integer,
  GDP integer,
  GO integer,
  FO integer,
  GO_FO numeric,
  primary key (Name, Season)
);

create table raw_team_offense_overall_inseason (
  Name varchar(30),
  Season integer,
  Date date,
  G integer,
  PA integer,
  AB integer,
  R integer,
  H integer,
  x2B integer,
  x3B integer,
  HR integer,
  RBI integer,
  BB integer,
  SO integer,
  SB integer,
  CS integer,
  AVG numeric,
  OBP numeric,
  SLG numeric,
  HBP integer,
  SF integer,
  SH integer,
  TB integer,
  XBH integer,
  GDP integer,
  GO integer,
  FO integer,
  GO_FO numeric,
  primary key (Name, Season, Date)
);

create table raw_team_pitching_conference (
  Name varchar(30),
  Season integer,
  G integer,
  IP varchar(20),
  H integer,
  R integer,
  ER integer,
  BB integer,
  SO integer,
  SO_9 numeric,
  HR integer,
  ERA numeric,
  primary key (Name, Season)
);

create table raw_team_pitching_conference_inseason (
  Name varchar(30),
  Season integer,
  Date date,
  G integer,
  IP varchar(20),
  H integer,
  R integer,
  ER integer,
  BB integer,
  SO integer,
  SO_9 numeric,
  HR integer,
  ERA numeric,
  primary key (Name, Season, Date)
);

create table raw_team_pitching_overall (
  Name varchar(30),
  Season integer,
  G integer,
  W integer,
  L integer,
  SV integer,
  CG integer,
  SHO integer,
  IP varchar(20),
  H integer,
  R integer,
  ER integer,
  BB integer,
  SO integer,
  ERA numeric,
  x2B integer,
  x3B integer,
  HR integer,
  AB integer,
  AVG numeric,
  WP integer,
  HBP integer,
  BK integer,
  SF integer,
  SH integer,
  SO_9 numeric,
  primary key (Name, Season)
);

create table raw_team_pitching_overall_inseason (
  Name varchar(30),
  Season integer,
  Date date,
  G integer,
  W integer,
  L integer,
  SV integer,
  CG integer,
  SHO integer,
  IP varchar(20),
  H integer,
  R integer,
  ER integer,
  BB integer,
  SO integer,
  ERA numeric,
  x2B integer,
  x3B integer,
  HR integer,
  AB integer,
  AVG numeric,
  WP integer,
  HBP integer,
  BK integer,
  SF integer,
  SH integer,
  SO_9 numeric,
  primary key (Name, Season, Date)
);
