name: Test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt
      - name: Lint
        run: bash scripts/lint.sh
      - name: Test
        run: pytest -v --cov --cov-report term
        env:
          # The hostname used to communicate with the PostgreSQL service container
          # PGHOST: localhost
          # The default PostgreSQL port
          # PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: postgres
